###  Exerc√≠cio 2 üöÄ
---

In [ ]:
import requests
import pandas as pd
from IPython.display import display  
import os
from dotenv import load_dotenv


load_dotenv()


api_key = os.getenv("TMDB_API_KEY")


url = f"https://api.themoviedb.org/3/movie/top_rated?api_key={api_key}&language=pt-BR"

response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    
    filmes = []
    for movie in data['results']:
        filmes.append({
            'T√≠tulo': movie['title'],
            'Nota': movie['vote_average'],
            'Data de Lan√ßamento': movie['release_date']
        })

    df = pd.DataFrame(filmes)
    display(df)
else:
    print("Erro na requisi√ß√£o:", response.status_code)

                                   T√≠tulo   Nota Data de Lan√ßamento
0                   Um Sonho de Liberdade  8.711         1994-09-23
1                       O Poderoso Chef√£o  8.700         1972-03-14
2             O Poderoso Chef√£o: Parte II  8.600         1974-12-20
3                    A Lista de Schindler  8.564         1993-12-15
4                12 Homens e uma Senten√ßa  8.548         1957-04-10
5                     A Viagem de Chihiro  8.537         2001-07-20
6          Batman: O Cavaleiro das Trevas  8.520         2008-07-16
7               Dilwale vai levar a noiva  8.517         1995-10-20
8                  √Ä Espera de um Milagre  8.506         1999-12-10
9                                Parasita  8.499         2019-05-30
10       Pulp Fiction: Tempo de Viol√™ncia  8.488         1994-09-10
11   O Senhor dos An√©is: O Retorno do Rei  8.485         2003-12-17
12                               Seu Nome  8.483         2016-08-26
13  Forrest Gump: O Contador de Hist√≥rias  8.468         1994-06-23
14                Tr√™s Homens em Conflito  8.461         1966-12-22
15                           Interestelar  8.455         2014-11-05
16                   Os Bons Companheiros  8.454         1990-09-12
17                       Os Sete Samurais  8.455         1954-04-26
18                 O T√∫mulo dos Vagalumes  8.400         1988-04-16
19                          A Vida √© Bela  8.447         1997-12-20